### ISSUE TITLE
Error during installation.

### ISSUE THREAD

**Issue by ilya-fiveisky** [Skycoder42/QtIFW-Advanced-Setup#1]
<img width="426" alt="capture" src="https://cloud.githubusercontent.com/assets/4052190/26468234/ab8ebbf4-4163-11e7-8c34-0619a373c6f9.PNG">

**Comment by Skycoder42** [comment]
This is an error with QPM, not QtIFW-Advanced-Setup. I created an issue there (see the reference). Please follow that issue and provide further information, if requested.

As a workaround, you can simply clone the git repository or download the sources from the release page, until this get's fixed in qpm. I'm sorry for the inconvenience

**Comment by 0xlitf** [comment]
I build the qpm by myself, it works.
go get qpm.io/qpm
go build qpm.io/qpm

evn: go 1.8.1 Windows 10
